src/GetJob.Web/ViewModels/Company/CompanyInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using GetJob.Models;

namespace GetJob.Web.ViewModels.Company
{
    public class CompanyInfoViewModel
    {
        public CompanyInfoViewModel()
        {
            
        }
        public CompanyInfoViewModel(Models.Company company)
        {
            Id = company.Id;
            Name = company.Name;
            CompanyFieldId = company.CompanyFieldId;
            CompanyField = company.CompanyField;
            CompanyScaleId = company.CompanyScaleId;
            CompanyScale = company.CompanyScale;
            Description = company.Description;
        }
        public string Id { get; set; } = Guid.NewGuid().ToString();
        [Required, StringLength(50), Display(Name = "企业名称")] public string Name { get; set; }
        [Required, Display(Name = "企业性质")] public int CompanyFieldId { get; set; }
        public CompanyField CompanyField { get; set; }
        [Required, Display(Name = "企业规模")] public int CompanyScaleId { get; set; }
        public CompanyScale CompanyScale { get; set; }
        [StringLength(450), Display(Name = "企业描述")] public string Description { get; set; }
    }
}

src/GetJob.Web/ViewModels/Company/CompanySignInViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GetJob.Web.ViewModels.Company
{
    public class CompanySignInViewModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

src/GetJob.Web/ViewModels/Company/CompanySignUpViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GetJob.Web.ViewModels.Company
{
    public class CompanySignUpViewModel
    {
        [Required, Display(Name = "手机")] public string PhoneNumber { get; set; }
        [Required, Display(Name = "用户名")] public string UserName { get; set; }
        [Required, Display(Name = "邮箱")] public string Mail { get; set; }
        [Required, Display(Name = "密码")] public string Password { get; set; }
        [Required, Display(Name = "公司名")] public string CompanyName { get; set; }
        [Required, Display(Name = "公司性质")] public int CompanyFieldId { get; set; }
        [Required, Display(Name = "公司规模")] public int CompanyScaleId { get; set; }
    }
}

src/GetJob.Web/ViewModels/Company/JobListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GetJob.Web.ViewModels.Company
{
    public class JobListViewModel
    {
        public JobListViewModel()
        {
            JobViewModels = new List<JobViewModel>();
        }


        public bool SelectedAll { get; set; }
        public List<JobViewModel> JobViewModels { get; set; }
    }
}

src/GetJob.Web/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace GetJob.Web.Controllers
{
    public class CandidateController : Controller
    {
        public IActionResult CandidateFollowList()
        {
            return View();
        }
        public IActionResult CandidateSearch()
        {
            return View();
        }
    }
}

src/GetJob.Web/Controllers/HireController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using GetJob.Models;
using GetJob.Services;
using GetJob.Web.ViewModels.Hire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace GetJob.Web.Controllers
{
    public class HireController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IJobService _jobService;
        private readonly ILocationService _locationService;
        private readonly IDegreeService _degreeService;
        private readonly IDeliverService _deliverService;
        private readonly ILogger<HireController> _logger;

        public HireController(ILogger<HireController> logger, ICompanyService companyService, IJobService jobService,
            ILocationService locationService, IDegreeService degreeService, IDeliverService deliverService)
        {
            _logger = logger;
            _companyService = companyService;
            _jobService = jobService;
            _locationService = locationService;
            _degreeService = degreeService;
            _deliverService = deliverService;
        }

        #region 公司部分
        /// <summary>
        /// 填充JobStatus下拉框
        /// </summary>
        /// <param name="selectedJobStatus">选择的JobStatusId</param>
        /// <returns></returns>
        [Authorize(Policy = "CompanyOnly")]
        private async Task PopulateJobStatusesDropDownList(string selectedJobStatus = null)
        {
            var jobStatuses = await _jobService.GetAllJobStatusAsync();
            ViewBag.JobStatuses = new SelectList(jobStatuses, "JobStatusId", "Text", selectedJobStatus);
        }

        [Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> HireJobManage(string searchString, string selectedJobStatus)
        {
            var company = await _companyService.GetByIdAsync(User.FindFirst("CompanyId").Value);
            var jobList = await _jobService.GetByCompanyAsync(company);
            if (!string.IsNullOrEmpty(searchString))
                jobList = jobList.Where(j =>
                        j.Name.Contains(searchString) || j.Company.Name.Contains(searchString) ||
                        j.Description.Contains(searchString))
                    .ToList();
            // TODO：是否需要在进入时显示所有招聘（如果后期数据变多 显示全部 页面数据会很多）
            if (string.IsNullOrEmpty(selectedJobStatus))
            {
                jobList = jobList.Where(j => j.JobStatus.JobStatusId == 1).ToList();
            }
            else
            {
                jobList = jobList.Where(j => j.JobStatus.JobStatusId == int.Parse(selectedJobStatus)).ToList();
            }
            var vm = new JobListViewModel();
            foreach (var job in jobList) vm.JobViewModels.Add(new JobViewModel(job));
            ViewBag.SearchString = searchString;
            await PopulateJobStatusesDropDownList(selectedJobStatus);
            return View(vm);
        }
        /// <summary>
        /// 返回工作类别（第二级）Json数据
        /// </summary>
        /// <param name="firstKindId">工作类别（第一级）</param>
        /// <returns>工作类别（第二级）Json数据</returns>
        [Authorize(Policy = "CompanyOnly")]
        public async Task<ActionResult> PopulateSecondKinds(int firstKindId)
        {
            var jobSecondKind = await _jobService.GetAllSecondKindAsync(firstKindId);
            return Json(jobSecondKind);
        }
        /// <summary>
        /// 返回城市字典Json数据
        /// </summary>
        /// <param name="provinceId">省份代码</param>
        /// <returns>城市字典Json数据</returns>
        [Authorize(Policy = "CompanyOnly")]
        public async Task<ActionResult> PopulateCities(int provinceId)
        {
            var cities = await _locationService.GetCityAsync(provinceId);
            return Json(cities);
        }
        /// <summary>
        /// 返回地区字典Json数据
        /// </summary>
        /// <param name="cityId">城市代码</param>
        /// <returns>地区字典Json数据</returns>
        [Authorize(Policy = "CompanyOnly")]
        public async Task<ActionResult> PopulateDistricts(int cityId)
        {
            var districts = await _locationService.GetDistrictAsync(cityId);
            return Json(districts);
        }
        /// <summary>
        /// 填充Job相关下拉框
        /// </summary>
        /// <param name="selectedJobCharacterId">已选择的JobCharacterId</param>
        /// <param name="selectedJobFirstKindId">已选择的JobFirstKindId</param>
        /// <param name="selectedJobKindId">已选择的JobKindId</param>
        /// <param name="selectedJobPayId">已选择的JobPayId</param>
        /// <param name="selectedJobStatusId">已选择的JobStatusId</param>
        /// <param name="selectedProvinceId">已选择的ProvinceId</param>
        /// <param name="selectedCityId">已选择的CityId</param>
        /// <param name="selectedDistrictId">已选择的DistrictId</param>
        /// <param name="selectedDegreeId">已选择的DegreeId</param>
        /// <returns></returns>
        private async Task PopulateJobRelatedDropDownList(string selectedJobCharacterId = null,
            string selectedJobFirstKindId = null, string selectedJobKindId = null, string selectedJobPayId = null,
            string selectedJobStatusId = null, string selectedProvinceId = null, string selectedCityId = null,
            string selectedDistrictId = null, string selectedDegreeId = null)
        {
            var jobCharacters = await _jobService.GetAllJobCharacterAsync();
            ViewBag.JobCharacters = new SelectList(jobCharacters, "JobCharacterId", "Text", selectedJobCharacterId);

            var jobFirstKinds = await _jobService.GetAllFirstKindAsync();
            ViewBag.JobFirstKinds = new SelectList(jobFirstKinds, "JobKindId", "Text", selectedJobFirstKindId);
            if (selectedJobFirstKindId != null)
            {
                var jobKinds = await _jobService.GetAllSecondKindAsync(int.Parse(selectedJobFirstKindId));
                ViewBag.JobKinds = new SelectList(jobKinds, "JobKindId", "Text", selectedJobKindId);
            }

            var jobPays = await _jobService.GetAllJobPayAsync();
            ViewBag.JobPays = new SelectList(jobPays, "JobPayId", "Text", selectedJobPayId);
            
            //TODO: 不不允许用户直接修改招聘状态，改成停止招聘按钮
            var jobStatuses = await _jobService.GetAllJobStatusAsync();
            ViewBag.JobStatuses = new SelectList(jobStatuses, "JobStatusId", "Text", selectedJobStatusId);

            var provinces = await _locationService.GetProvinceAsync();
            ViewBag.Provinces = new SelectList(provinces, "LocationId", "Text", selectedProvinceId);

            if (selectedProvinceId != null)
            {
                var cities = await _locationService.GetCityAsync(int.Parse(selectedProvinceId));
                ViewBag.Cities = new SelectList(cities, "LocationId", "Text", selectedCityId);
            }

            if (selectedCityId != null)
            {
                var districts = await _locationService.GetDistrictAsync(int.Parse(selectedCityId));
                ViewBag.Districts = new SelectList(districts, "LocationId", "Text", selectedDistrictId);
            }

            var degrees = await _degreeService.GetAllAsync();
            ViewBag.Degrees = new SelectList(degrees, "DegreeId", "Text", selectedDistrictId);
        }

        [Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> HireJobPublish()
        {
            await PopulateJobRelatedDropDownList();
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> HireJobPublish(JobViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var job = new Job
                {
                    Name = vm.Name,
                    CompanyId = vm.CompanyId,
                    JobCharacterId = vm.JobCharacterId,
                    JobKindId = vm.JobKindId,
                    JobPayId = vm.JobPayId,
                    JobStatusId = vm.JobStatusId,
                    LocationId = vm.LocationId,
                    DegreeId = vm.DegreeId,
                    RecruitNumber = vm.RecruitNumber,
                    Description = vm.Description,
                    LastModify = DateTime.Now
                };
                await _jobService.AddJobAsync(job);
                return RedirectToAction(nameof(HireJobManage));
            }

            await PopulateJobRelatedDropDownList(vm.JobCharacterId.ToString(), vm.JobFirstKindId.ToString(),
                vm.JobKindId.ToString(), vm.JobPayId.ToString(), vm.JobStatusId.ToString(), vm.ProvinceId.ToString(),
                vm.CityId.ToString(), vm.LocationId.ToString(), vm.DegreeId.ToString());
            return View(vm);
        }

        [Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> HireJobEdit(string id = null)
        {
            if (id == null) return NotFound();
            var job = await _jobService.GetByIdAsync(id);
            if (job == null) return NotFound();
            var vm = new JobViewModel(job);
            await PopulateJobRelatedDropDownList(vm.JobCharacterId.ToString(), vm.JobFirstKindId.ToString(),
                vm.JobKindId.ToString(), vm.JobPayId.ToString(), vm.JobStatusId.ToString(), vm.ProvinceId.ToString(),
                vm.CityId.ToString(), vm.LocationId.ToString(), vm.DegreeId.ToString());
            return View(vm);
        }

        [HttpPost]
        [Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> HireJobEdit(JobViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var job = new Job
                {
                    Id = vm.Id,
                    Name = vm.Name,
                    CompanyId = vm.CompanyId,
                    JobCharacterId = vm.JobCharacterId,
                    JobKindId = vm.JobKindId,

src/GetJob.Web/Controllers/RecruiterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GetJob.Services;
using GetJob.Web.Helper;
using GetJob.Web.ViewModels.Recruiter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GetJob.Web.Controllers
{
    public class RecruiterController : Controller
    {
        private readonly IUserService _userService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public RecruiterController(IUserService userService, IWebHostEnvironment webHostEnvironment)
        {
            _userService = userService;
            _webHostEnvironment = webHostEnvironment;
        }
        [Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> PersonalInfo()
        {
            var user = await _userService.GetByUserNameAsync(User.Identity.Name);
            var vm = new UserInfoViewModel(user)
            {
                HeaderUrl = await _userService.GetUserClaimAsync(user.UserName, "HeaderUrl")
            };
            return View(vm);
        }
        [HttpPost, Authorize(Policy = "CompanyOnly")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PersonalInfoChangeHeader(UserInfoViewModel vm, IFormFile headerFile)
        {
            if (ModelState.IsValid)
            {
                var user = await _userService.GetByUserNameAsync(User.Identity.Name);
                var fileName = await FileHelper.UploadFileAsync(headerFile, _webHostEnvironment.WebRootPath + @$"\upload\header\");
                vm.HeaderUrl = @"\upload\header\" + fileName;
                await _userService.UpdateUserClaimAsync(user.UserName, "HeaderUrl", vm.HeaderUrl);
                return RedirectToAction(nameof(PersonalInfo), vm);
            }
            ModelState.AddModelError("", "未知错误");
            return RedirectToAction(nameof(PersonalInfo));
        }
        [Authorize(Policy = "CompanyOnly")]
        public IActionResult RecruiterInfo()
        {
            return View();
        }
        [Authorize(Policy = "CompanyOnly")]
        public IActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost, Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel vm)
        {
            var result = await _userService.ChangePassword(User.Identity.Name, vm.OldPassword, vm.NewPassword);
            if (result.Succeeded)
            {
                return View("_PasswordChangeSuccess");
            }
            ModelState.AddModelError("PasswordError", "密码错误");
            return View(vm);
        }
        [HttpPost, Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> ChangeEmail(string emailAddress)
        {
            var user = await _userService.GetByUserNameAsync(User.Identity.Name);
            user.Email = emailAddress;
            return Json(await _userService.UpdateAsync(user));
        }
        [HttpPost, Authorize(Policy = "CompanyOnly")]
        public async Task<IActionResult> ChangePhoneNumber(string phoneNumber)
        {
            var user = await _userService.GetByUserNameAsync(User.Identity.Name);
            user.PhoneNumber = phoneNumber;
            return Json(await _userService.UpdateAsync(user));
        }
    }
}

src/GetJob.Web/Views/Shared/_Company.cshtml
@{
    Layout = "_Empty";
}
<partial name="_NavBar"/>

<div class="container">
    <div class="row">
        <nav id="sidebarMenu" class="col-lg-2 d-md-block sidebar collapse" style="background-color: #F8F9FA">
            <div class="sidebar-sticky py-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" data-toggle="collapse" href="#multiCollapse2" aria-expanded="false" aria-controls="multiCollapse2">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-journal-text mr-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
                                <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
                                <path fill-rule="evenodd" d="M5 10.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
                            </svg>
                            招聘管理
                        </a>
                        <div class="collapse @(ViewBag.Title == "岗位管理" || ViewBag.Title == "岗位发布" || ViewBag.Title == "简历审核" || ViewBag.Title == "招聘历史" ? "show" : "") p-0 fs-5" id="multiCollapse2">
                            <a class="dropdown-item @(ViewBag.Title == "岗位管理" ? "active" : "")" asp-controller="Hire" asp-action="HireJobManage">岗位管理</a>
                            <a class="dropdown-item @(ViewBag.Title == "岗位发布" ? "active" : "")" asp-controller="Hire" asp-action="HireJobPublish">岗位发布</a>
                            <a class="dropdown-item @(ViewBag.Title == "简历审核" ? "active" : "")" asp-controller="Hire" asp-action="HireResumeList">简历审核</a>
                            <a class="dropdown-item @(ViewBag.Title == "招聘历史" ? "active" : "")" asp-controller="Hire" asp-action="HireHistory">招聘历史</a>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" data-toggle="collapse" href="#multiCollapse3" aria-expanded="false" aria-controls="multiCollapse3">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-building mr-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694L1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z" />
                                <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z" />
                            </svg>
                            企业管理
                        </a>
                        <div class="collapse @(ViewBag.Title == "企业信息" ? "show" : "") p-0 fs-5" id="multiCollapse3">
                            <a class="dropdown-item @(ViewBag.Title == "企业信息" ? "active" : "")" asp-controller="Company" asp-action="CompanyInfo">企业信息</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" data-toggle="collapse" href="#multiCollapse4" aria-expanded="false" aria-controls="multiCollapse4">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search mr-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                                <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                            </svg>
                            应聘者关注
                        </a>
                        <div class="collapse @(ViewBag.Title == "关注列表" || ViewBag.Title == "搜索应聘者" ? "show" : "") p-0 fs-5" id="multiCollapse4">
                            <a class="dropdown-item @(ViewBag.Title == "关注列表" ? "active" : "")" asp-controller="Candidate" asp-action="CandidateFollowList">关注列表</a>
                            <a class="dropdown-item @(ViewBag.Title == "搜索应聘者" ? "active" : "")" asp-controller="Candidate" asp-action="CandidateSearch">搜索应聘者</a>
                        </div>
                    </li>

                    <li class="nav-item font-weight-bold">
                        <a class="nav-link" data-toggle="collapse" href="#multiCollapse6" aria-expanded="false" aria-controls="multiCollapse6">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person mr-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                            </svg>
                            我的资料
                        </a>
                        <div class="collapse @(ViewBag.Title == "基本信息" || ViewBag.Title == "职位信息" || ViewBag.Title == "密码修改" ? "show" : "") p-0 fs-5" id="multiCollapse6">
                            <a class="dropdown-item @(ViewBag.Title == "基本信息" ? "active" : "")" asp-controller="Recruiter" asp-action="PersonalInfo">基本信息</a>
                            <a class="dropdown-item @(ViewBag.Title == "职位信息" ? "active" : "")" asp-controller="Recruiter" asp-action="RecruiterInfo">职位信息</a>
                            <a class="dropdown-item @(ViewBag.Title == "密码修改" ? "active" : "")" asp-controller="Recruiter" asp-action="ChangePassword">密码修改</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <main role="main" class="col-lg-10 px-md-4 py-md-4">
            @RenderBody()
        </main>
    </div>
</div>
<script>
    $('.collapse').on('show.bs.collapse', function () {
        $('.collapse').collapse('hide');
    })
</script>

src/GetJob.Web/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-xl">
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarsExample07XL">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Job">职位</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Company">公司</a>
                </li>
            </ul>
            <ul class="navbar-nav justify-content-end">
                @*@User.Claims.Any(c => c.Type == "Company")*@
                @if (!User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Student" asp-action="SignUp">我要找工作</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Company" asp-action="SignUp">我要招聘</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="SignIn">登录</a>
                    </li>
                }
                else
                {
                    @if (User.Claims.Any(i => i.Type == "Identity" && i.Value == "Company"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Hire" asp-action="HireJobManage">企业后台</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Hire" asp-action="HireJobPublish">发布岗位</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-toggle="dropdown" aria-expanded="false">
                                <img class="user-header radius" src="@User.Claims.FirstOrDefault(c => c.Type=="HeaderUrl")?.Value" width="30" height="30"/>
                                @User.Identity.Name
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdown07XL">
                                <a class="dropdown-item" asp-controller="Recruiter" asp-action="PersonalInfo">个人信息</a>
                                <a class="dropdown-item" asp-controller="Recruiter" asp-action="RecruiterInfo">职位信息</a>
                                <a class="dropdown-item" asp-controller="Recruiter" asp-action="ChangePassword">密码修改</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="Logout">登出</a>
                            </div>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</nav>